#nullable enable

using System;
using System.Collections.Generic;
using System.Reflection;
using UnityEditor;
using VContainer;
using VContainer.Diagnostics;
using VContainer.Unity;

namespace VContainerPlus.Editor
{
    /// <summary>
    /// Validator for checking dependencies in VContainer lifetime scopes.
    /// </summary>
    public static class DependencyValidator
    {
        /// <summary>
        /// Validates the specified lifetime scope for dependency injection issues.
        /// </summary>
        /// <param name="lifetimeScope">The lifetime scope to validate.</param>
        /// <param name="useSourceGeneration">Whether to check if registered types can be generated by VContainer.</param>
        /// <returns>A validation result containing any errors found.</returns>
        public static ValidateResult Validate(LifetimeScopeBase lifetimeScope, bool useSourceGeneration = true)
        {
            var builder = new DebugContainerBuilder(lifetimeScope);
            var result = new ValidateResult();

            // Check if the Configure method is called and the auto bind components are registered.
            if (!lifetimeScope.TryConfigureDebug(builder))
            {
                result.AddFail(lifetimeScope.GetType(), "Configure method is not called. Please call base in the overridden Configure method.");
            }

            // Check if the registered types can be generated by VContainer.
            if (useSourceGeneration)
            {
                var generateTypes = TypeCache.GetTypesDerivedFrom<IInjector>();
                foreach (var type in builder.GetRegisteredTypes())
                {
                    if (!generateTypes.Contains(type))
                    {
                        result.AddFail(type, "It is not a type that can be generated by VContainer.");
                    }
                }
            }
            return result;
        }

        /// <summary>
        /// A debug container builder that collects registration information without building an actual container.
        /// </summary>
        private sealed class DebugContainerBuilder : IContainerBuilder
        {
            private readonly List<RegistrationBuilder> _registrationBuilders = new();

            public object? ApplicationOrigin { get; set; }

            int IContainerBuilder.Count => _registrationBuilders.Count;

            RegistrationBuilder IContainerBuilder.this[int index]
            {
                get => _registrationBuilders[index];
                set => _registrationBuilders[index] = value;
            }

            DiagnosticsCollector IContainerBuilder.Diagnostics
            {
                get => throw new NotImplementedException();
                set => throw new NotImplementedException();
            }

            public DebugContainerBuilder(object applicationOrigin)
            {
                ApplicationOrigin = applicationOrigin;
            }

            /// <summary>
            /// Gets all registered types excluding components and instances.
            /// </summary>
            /// <returns>An enumerable of registered types.</returns>
            public IEnumerable<Type> GetRegisteredTypes()
            {
                foreach (var builder in _registrationBuilders)
                {
                    if (builder is ComponentRegistrationBuilder || builder.GetType().FullName == "VContainer.Internal.InstanceRegistrationBuilder")
                    {
                        continue;
                    }

                    yield return GetImplementationType(builder);
                }
            }

            T IContainerBuilder.Register<T>(T registrationBuilder)
            {
                _registrationBuilders.Add(registrationBuilder);
                return registrationBuilder;
            }

            void IContainerBuilder.RegisterBuildCallback(Action<IObjectResolver> container)
            {
            }

            bool IContainerBuilder.Exists(Type type, bool includeInterfaceTypes, bool findParentScopes)
            {
                foreach (var builder in _registrationBuilders)
                {
                    if (GetImplementationType(builder) == type ||
                        includeInterfaceTypes && GetInterfaceTypes(builder)?.Contains(type) == true)
                    {
                        return true;
                    }
                }
                return false;
            }

            /// <summary>
            /// Gets the implementation type from a registration builder using reflection.
            /// </summary>
            /// <param name="builder">The registration builder.</param>
            /// <returns>The implementation type.</returns>
            static Type GetImplementationType(RegistrationBuilder builder)
            {
                var field = typeof(RegistrationBuilder).GetField(
                    "ImplementationType",
                    BindingFlags.Instance | BindingFlags.NonPublic
                );
                return (Type)field!.GetValue(builder);
            }

            static List<Type>? GetInterfaceTypes(RegistrationBuilder builder)
            {
                var field = typeof(RegistrationBuilder).GetField(
                    "InterfaceTypes",
                    BindingFlags.Instance | BindingFlags.NonPublic
                );
                return (List<Type>?)field!.GetValue(builder);
            }
        }
    }
}