name: unity-meta-check
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
    paths:
      - src/VContainerPlus.Unity/Assets/**
      - src/VContainerPlus.Unity/Packages/**
  workflow_dispatch: {}

jobs:
  meta-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        # ghasec-ignore: unpinned-action
        uses: AndanteTribe/Actions/actions/checkout@main # zizmor: ignore[unpinned-uses] repository-local action reference is intentionally tracked on @main
        with:
          submodules: false
          lfs: true
      - name: Unity meta files check (github-hosted ubuntu-latest)
        # ghasec-ignore: unpinned-action
        uses: AndanteTribe/Actions/actions/unity-meta-check@main # zizmor: ignore[unpinned-uses] repository-local action reference is intentionally tracked on @main
        with:
          target_path: src/VContainerPlus.Unity
